// This code was generated by `SqlHydra.SqlServer` -- v3.5.0.
namespace SqlHydraAndFSharpCore

open SqlHydra
open SqlHydra.Query

module Version =
    let cli = System.Version(3, 5, 0)
    let ns = "SqlHydraAndFSharpCore"
    SqlHydra.Query.VersionCheck.assertIsCompatible cli ns

module dbo =

    [<CLIMutable>]
    type table1 =
        { [<ProviderDbType("UniqueIdentifier")>]
          id: System.Guid
          [<ProviderDbType("NVarChar")>]
          data_value: string }

    let table1 = table<table1>

    [<CLIMutable>]
    type table2 =
        { [<ProviderDbType("UniqueIdentifier")>]
          table1_id: System.Guid
          [<ProviderDbType("Date")>]
          date: System.DateOnly
          [<ProviderDbType("DateTime2")>]
          timestamp: System.DateTime }

    let table2 = table<table2>

module sys =

    [<CLIMutable>]
    type database_firewall_rules =
        { [<ProviderDbType("Int")>]
          id: int
          [<ProviderDbType("NVarChar")>]
          name: string
          [<ProviderDbType("VarChar")>]
          start_ip_address: string
          [<ProviderDbType("VarChar")>]
          end_ip_address: string
          [<ProviderDbType("DateTime")>]
          create_date: System.DateTime
          [<ProviderDbType("DateTime")>]
          modify_date: System.DateTime }

    let database_firewall_rules = table<database_firewall_rules>


[<System.Obsolete("The HydraReader module is no longer needed and will be removed in v4.0.")>]
type HydraReader =
    static member Read(reader: Microsoft.Data.SqlClient.SqlDataReader) : (unit -> 'T) =
        Hydration.buildRowReader<'T> Domain.ProviderType.SqlServer reader


[<System.Obsolete("The HydraBuilders module is no longer needed and will be removed in v4.0.")>]
module HydraBuilders =
    ()


type QueryContextFactory =
    { OpenContext: unit -> QueryContext
      OpenContextAsync: unit -> System.Threading.Tasks.Task<QueryContext> }

    interface IQueryContextFactory with
        member this.OpenContextAsync() = this.OpenContextAsync()

    static member Create(connectionString: string, ?sqlLogger) =
        let compiler = SqlKata.Compilers.SqlServerCompiler()

        let createConn () : System.Data.Common.DbConnection =
            new Microsoft.Data.SqlClient.SqlConnection(connectionString)

        let openContext () =
            let conn = createConn ()
            conn.Open()
            let ctx = new QueryContext(conn, compiler)
            sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
            ctx

        let openContextAsync () =
            task {
                let conn = createConn ()
                do! conn.OpenAsync()
                let ctx = new QueryContext(conn, compiler)
                sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
                return ctx
            }

        { OpenContext = openContext
          OpenContextAsync = openContextAsync }
