module SqlHydraAndFSharpCore.SqliteTestDatabase
// This file autogenerated by the powershell script in this directory

let schema =
    """
/* Used to create the SqlServer database that Schema.fs is generated from */

CREATE TABLE [dbo].[table1]
(
  id [blob] NOT NULL,
  data_value [text] NOT NULL,

  CONSTRAINT pk_table1 PRIMARY KEY (id)
);

CREATE TABLE [dbo].[table2]
(
  table1_id [blob] NOT NULL,
  date [text] NOT NULL,
  timestamp [text] NOT NULL,

  CONSTRAINT pk_table2 PRIMARY KEY (table1_id, date, timestamp)
);
"""
