name: ShowProblem

on:
  - pull_request
  - workflow_dispatch

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up .net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0"

      - name: Build
        shell: bash
        run: |
          dotnet build

      - name: Run
        shell: bash
        run: dotnet run
